adds persistence for undo/redo actions
cybersemics/em pull request #1039
Opened 2021-02-15 17:59 UTC by anmolarora1

#987 

As per the discussion [here](https://github.com/cybersemics/em/issues/987#issuecomment-771038879), implemented the persistence for undo/redo actions by calling `updateThoughts` from the undoRedoReducerEnhancer - 
We're extracting thought and context index updates from the undo/redo patches, passing them to the `updateThoughts` reducer, and merging the resulting state with the state returned by the undo/redo reducer.

2021-02-18 14:59 UTC, raineorshine requested changes

2021-02-18 14:59 UTC, raineorshine commented on src/shortcuts/__tests__/undo.ts
> +  initialize()
`initialize` is async and needs to be awaited

2021-02-18 14:59 UTC, raineorshine commented on src/shortcuts/__tests__/undo.ts
> +  await fakeTimer.runAllAsync()
Maybe this can be removed and the actions can be combined into one dispatch once `initialize` is awaited?

2021-02-18 14:59 UTC, raineorshine commented on src/shortcuts/__tests__/undo.ts
> +  await fakeTimer.runAllAsync()
Try `await initialize()` here as well

2021-02-18 14:59 UTC, raineorshine commented on src/redux-enhancers/undoRedoReducerEnhancer.ts
> +const extractUpdates = (patch: Patch, newState: State) => {
Think of any function that takes a `State` and returns a new `State` as a reducer. `state: State` should be the first argument by convention.

2021-02-18 14:59 UTC, raineorshine commented on src/redux-enhancers/undoRedoReducerEnhancer.ts
> +  return updateThoughts({ thoughtIndexUpdates, contextIndexUpdates })(newState)
Nice, this looks great

2021-02-18 14:59 UTC, raineorshine commented on src/redux-enhancers/undoRedoReducerEnhancer.ts
> +  return { ...newState, ...asyncUpdates }
Note that you could also use `reducerFlow` here to generate the new state.

2021-02-23 17:15 UTC, anmolarora1 commented
@raineorshine You pointed out correctly that the `initialize` is an async function and needs to be called using await. But waiting for the initialize function twice in a test exceeds the jest's default timeout threshold of `5000ms`. We should be able to fix that with some updates to our jest config, but I don't think a test should take more than 5s. 
Furthermore, I noticed that we're not awaiting for `initialize` call in [the tests for pullQueue](https://github.com/cybersemics/em/blob/5f6c27167372dd834cf188c9204fdff530e069c6/src/redux-middleware/__tests__/pullQueue.ts#L24), and adding `await` to them made them fail as well with the same timeout reason.
However, every call to initialize is followed by ```await fakeTimer.runAllAsync()```, and I suppose that's been added to handle async initialize call without breaking jest's timeout. [Here's](https://github.com/cybersemics/em/issues/919#issuecomment-739135971) an excellent explanation written by @shresthabijay , where he's mentioned that it's the Sinon's fake timers (precisely, the `runAllAsync` function in this case) that help us avoid the timeout failures related to `dexie`. 
So as per my understanding of it, we probably don't need to await those calls. Let me know what you think.

2021-02-24 17:08 UTC, raineorshine commented on src/shortcuts/__tests__/undo.ts
> +  initialize()
Let's call `await fakeTimer.runAllAsync` immediately after.

2021-02-24 17:13 UTC, raineorshine commented
> @raineorshine You pointed out correctly that the `initialize` is an async function and needs to be called using await. But waiting for the initialize function in a test exceeds the jest's default timeout threshold of `5000ms`. We should be able to fix that with some updates to our jest config, but I don't think a test should take more than 5s.
> Furthermore, I noticed that we're not awaiting for `initialize` call in [the tests for pullQueue](https://github.com/cybersemics/em/blob/5f6c27167372dd834cf188c9204fdff530e069c6/src/redux-middleware/__tests__/pullQueue.ts#L24), and adding `await` to them made them fail as well with the same timeout reason.

Ah, thanks for the reminder! I had all sorts of trouble with timers before Bijay found a fix.

> [Here's](https://github.com/cybersemics/em/issues/919#issuecomment-739135971) an excellent explanation written by @shresthabijay , where he's mentioned that it's the Sinon's fake timers (precisely, the `runAllAsync` function in this case) that help us avoid the timeout failures related to `dexie`.

Beautiful. Let's add a comment that points to that comment so that others (i.e. me) do not forget the reasoning behind `runAllAsync`.

> So as per my understanding of it, we probably don't need to await those calls. Let me know what you think.

Yup, I understand now. Are you able to move the `runAllAsync` to immediately after `initialize`? It would be cleaner to have all the actions batched together in one dispatch since they are contiguous.

2021-02-25 16:36 UTC, raineorshine approved these changes

2021-02-25 16:36 UTC, merged