Unroot context before getting value of sort attribute
cybersemics/em pull request #1083
Opened 2021-04-09 19:56 UTC by onurpolattimur

Fixes: #1080 

We need to unroot the context before getting value of sorting attribute for the context because root token is removed from the context when adding. 

https://github.com/cybersemics/em/blob/e2c66a7c0b46127f43c2978145b490aed0e0458b/src/reducers/toggleAttribute.ts#L35

2021-04-10 14:56 UTC, raineorshine requested changes
Thank you! Could you add the test to https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/toggleSort.ts?

2021-04-11 11:49 UTC, raineorshine commented
Oops, I just realized that a pure state test won't suffice (it passes even if the change is reverted). We need to test the DOM since that is where the bug is.

I would suggest an RTL test like in https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/extractThought.ts which will allow you to test the order of the subthoughts. Is this something you'd like to try, or should I add it?

2021-04-11 17:56 UTC, onurpolattimur commented
> Oops, I just realized that a pure state test won't suffice (it passes even if the change is reverted). We need to test the DOM since that is where the bug is.
> 
> I would suggest an RTL test like in https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/extractThought.ts which will allow you to test the order of the subthoughts. Is this something you'd like to try, or should I add it?

Yes, you are right. I wrote the RTL tests but  I didn't find any RTL tests regarding sorting. Where should we put the tests?

2021-04-11 18:16 UTC, raineorshine commented
You can put them in `/src/shortcuts/__tests__/toggleSort.ts` with the non-RTL tests. Thanks!

2021-04-11 18:58 UTC, onurpolattimur commented
I have added the tests. Can you review it please?

2021-04-12 12:35 UTC, raineorshine commented
Thank you! The tests are still giving me a false positive when I revert them. Any ideas why? They look good to me, and they're clearly testing the sort order in the DOM.

2021-04-12 16:51 UTC, onurpolattimur commented
Are you sure? Which file did you revert? When I revert the changes in `getSortPreference.ts`, the home context RTL test ('thoughts are sorted alphabetically') is failed.

2021-04-12 22:31 UTC, raineorshine commented
Ah, I'm glad I asked! I must have run the wrong test or it didn't build properly. I was able to fail it this time! Tests work perfectly. (Always amusing when the fix is 1 line of code and the tests are 100 😆.)

Thanks again for your contribution!

2021-04-12 22:31 UTC, merged