Data integrity Issue Fix
cybersemics/em pull request #1097
Opened 2021-04-19 15:01 UTC by shresthabijay

fixes #1069 #1095 #1096

# Changes

- Update `existingThoughtChange` and `exisitingThoughtMove` to fix data integrity issue.
- Add tests specific to these issues.

2021-04-19 15:04 UTC, shresthabijay commented
@raineorshine I have made the changes. Please review it. Thanks!

I have added a selector called `checkDataIntegrity` which is used in data integrity tests. It is basically `fixContextIndex`  but returns `contextIndex` updates if there are missing lexemes. Since the majority code is redundant between `fixContextIndex` and `checkDateIntegrity` should I expose the `fixContextIndex` to the `window.em`?

2021-04-21 11:02 UTC, raineorshine commented
> I have added a selector called `checkDataIntegrity` which is used in data integrity tests. It is basically `fixContextIndex` but returns `contextIndex` updates if there are missing lexemes. Since the majority code is redundant between `fixContextIndex` and `checkDateIntegrity` should I expose the `fixContextIndex` to the `window.em`?

You can remove `fixContextIndex`. It's no longer useful now that not all thoughts are loaded into memory.

2021-04-21 11:13 UTC, raineorshine requested changes
Looks good! Much needed. Thanks again!

2021-04-21 11:13 UTC, raineorshine commented on src/selectors/checkDataIntegrity.ts
> +const checkDataIntegrity = (state: State, max = 100000) => {
Since `checkDataIntegrity` is only used in tests, we should put it in `/test-helpers` in order to keep `/selectors` just for runtime functions.

2021-04-21 11:13 UTC, raineorshine commented on src/selectors/checkDataIntegrity.ts
> + */
This comment is no longer relevant and can be deleted.

2021-04-26 12:53 UTC, merged