Don't set caret when user click an Editable
cybersemics/em pull request #1125
Opened 2021-05-06 16:00 UTC by onurpolattimur

fixes: #981 
_____
> Why do we set the caret?
> 
> On events that don't contain user clicks, we should set the caret for editable elements. Because the user doesn't click anywhere but we want the caret to be on a thought. Here are some examples of this situation;
> 
> - When we refresh the page, the caret should be on the thought in the path.
> - When we delete a thought, the caret should be on the previous thought.
> - When we add a thought, the caret should be on the newly created thought.
> ....
> What should we do?
> 
> We should not set the caret if we want to see that the caret on the correct position where the user clicks. Because the browser already set the caret where the user clicks. The only thing we should know before setting caret is whether the user clicked or not.

2021-05-07 19:06 UTC, raineorshine requested changes
Tested on mobile, works great! Very low footprint, well done.

I just found one regression on desktop.

## Steps to Reproduce

1. Create a thought
2. Refresh the page
3. Click on the thought

## Current Behavior

`5bd9895a8`

Cursor moves to thought but caret is not set.

## Expected Behavior

`dev`

Caret should always be set on the cursor on desktop.

2021-05-07 19:06 UTC, raineorshine commented on src/components/Editable.tsx
> +    isTapped && setIsTapped(false)
Let's stick with explicit `if` statements on expressions with side effects. I'm not strictly opposed to the shorthand, but it deviates from the convention we have been using so I'd like to stay consistent for now.

2021-05-07 19:06 UTC, raineorshine commented on src/components/Editable.tsx
> +    setIsTapped(true)
When adding behavior like this that may not be obvious to other developers, it might be good to leave a descriptive comment and link to the issue.

2021-05-07 20:36 UTC, onurpolattimur commented
Hi @raineorshine, I found the root cause of the issue you wrote. We are using e.preventDefault() in onTap. Because `state.editing` is false after refreshing the page `editingOrOnCursor` is also false, so it is preventing onFocus event and caret can not be set by the browser. I fixed, can you review it again?

2021-05-07 21:03 UTC, raineorshine approved these changes
Works great! Thanks!

Do you think it would be possible to produce a failing e2e test case?

https://github.com/cybersemics/em/blob/dev/src/browser.ts#L5-L6

2021-05-08 18:47 UTC, onurpolattimur commented
> Works great! Thanks!
> 
> Do you think it would be possible to produce a failing e2e test case?
> 
> https://github.com/cybersemics/em/blob/dev/src/browser.ts#L5-L6

Hi @raineorshine, I added the e2e test for the issue that you wrote above. But unfortunately, we can not write an e2e  test for the issue #981, because it occurs only on the mobile browsers.  It doesn't matter whether isTouch true or false. We can not produce this issue on our desktop browser with forcing isTouch true .

2021-05-10 21:39 UTC, raineorshine commented
> > Works great! Thanks!
> > Do you think it would be possible to produce a failing e2e test case?
> > [https://github.com/cybersemics/em/blob/dev/src/browser.ts#L5-L6](https://github.com/cybersemics/em/blob/dev/src/browser.ts?rgh-link-date=2021-05-08T18%3A47%3A41Z#L5-L6)
> 
> Hi @raineorshine, I added the e2e test for the issue that you wrote above.

I'm not able to get the test to fail on `dev`. Do you experience otherwise?

> But unfortunately, we can not write an e2e test for the issue #981, because it occurs only on the mobile browsers. It doesn't matter whether isTouch true or false. We can not reproduce this issue on our desktop browser with forcing isTouch true .

Got it, makes sense.

2021-05-10 21:54 UTC, merged