Activate cursorBack when clicking the hidden thought
cybersemics/em pull request #1128
Opened 2021-05-07 18:53 UTC by onurpolattimur

fixes: #1029 

____

This issue occurs because we are clicking the editable are of hidden thoughts. I added border for .editable class to show you the boundaries of editable elements.

![image](https://user-images.githubusercontent.com/23136437/117495390-38e1e300-af7e-11eb-9683-b39eb99a73c7.png)

There is already a function written for handle this situation `isElementHiddenByAutoFocus` . But the problem was in tap handler, it was not entering the if block because `editingOrOnCursor` is true when we click the area of `d`

https://github.com/cybersemics/em/blob/e30375659d5d5ad98c5df5bbe88f3e9a7d92ff1d/src/components/Editable.tsx#L612-L630

I was thinking solve this issue with css `visible: hidden` property but this will cause other issues. For example, if we add  `.distance-from-cursor-3 > .child { visibility: hidden }`then we can not see the thoughts in `.distance-from-cursor-3` We were going to need to add other css properties for visible thughts in `.distance-from-cursor-3`

2021-05-07 19:21 UTC, raineorshine requested changes
I appreciate the succinct description of the cause of the problem, existing infrastructure, and choice of solution. I tested and it fixes the issue, but it unfortunately breaks a test case when tapping on an uncle.

## Steps to Reproduce

```
- a
  - b
    - c
  - d
``` 

(`d` is indented one level compared to the original test case in #1029.)

1. Set the cursor on `c`
2. Tap one line height below `c`, just to the right of where `d` would be. 

## Current Behavior

Cursor moves to `a`. 

## Expected Behavior

Cursor and caret should move to `d`.

2021-05-08 15:25 UTC, onurpolattimur commented
Hi @raineorshine, I reproduced your issue and I saw that onClick event of the Content div triggered.  First, I suspected event bubbling, but it was not. In onTap of Editable we have already prevented the default events. 

The problem was that if we click the thought '**d**', the '**b**' thought will be collapsed and the place where we touch up is on `Content` element and this will trigger the onClick event of `Content`.

2021-05-08 17:34 UTC, onurpolattimur commented on src/components/Content.tsx
> +    if (e.target.id !== 'content') {
I couldn't get id from `React.MouseEvent` so I used `any` for here.

2021-05-10 20:50 UTC, raineorshine requested changes
Fix one regression and two more pop up 😂! Tested on iOS.

f54684140 results in incorrect behavior when clicking on empty space.

Can you see if this is reproducible on desktop with `isTouch = true`? That will tell us if we can write an e2e case for this as well.

## Steps to Reproduce

```
- a
  - b
    - c
  - d
``` 

1. Set the cursor on `c`
2. Tap on empty space below `d`

## Current Behavior

If edit mode is enabled, edit mode is disabled and the cursor doesn't move.
If edit mode is disabled, the cursor moves to `a`. 

## Expected Behavior

Cursor and caret should move to `d`.

2021-05-10 20:51 UTC, raineorshine commented
> Hi @raineorshine, I reproduced your issue and I saw that onClick event of the Content div triggered. First, I suspected event bubbling, but it was not. In onTap of Editable we have already prevented the default events.

I apologize if I am misunderstanding, but `preventDefault` doesn't have any effect on event bubbling. `e.preventDefault()` prevents the default browser behavior (such as navigating to the `href` of an `<a>`) and `e.stopPropagation()` prevents the same event from firing on ancestors (event bubbling). Here's a Code Sandbox that demonstrates this more clearly: https://codesandbox.io/s/divine-morning-0cw49?file=/src/App.js.

> The problem was that if we click the thought '**d**', the '**b**' thought will be collapsed and the place where we touch up is on `Content` element and this will trigger the onClick event of `Content`.

I'm not sure I understand yet. Can you explain this more? What happens before the `Content` onClick and why does it get that far?

2021-05-10 22:19 UTC, onurpolattimur commented
Yes, but e.stopPropogation() doesn't work for touch events. But we can prevent event bubbling using e.preventDefault() for touch events. Here is an example for you, you can test in https://qf8e8.csb.app/ with forcing mobile view by developer tools.
Source codes: https://codesandbox.io/s/withered-water-qf8e8?file=/src/App.js

But our problem was not about event bubbling. I will try to explain more clearly.
First of all, onClick events are triggered after we release the mouse button or release the touch. 

```
- a
  - b
    - c
  - d
```
Think about the case above, when the cursor is on `c` and we touch the thought 'd', context 'b' will be collapsed, and We won't have released the touch yet, the current touch position will be on Content div, and after we release the touch, the onClick event of Content div will be triggered.

I will also look into the case you wrote and will try to make some explanation.

2021-05-10 22:31 UTC, raineorshine commented
> Yes, but e.stopPropogation() doesn't work for touch events. But we can prevent event bubbling using e.preventDefault() for touch events. Here is an example for you, you can test in [qf8e8.csb.app](https://qf8e8.csb.app/) with forcing mobile view by developer tools.
> Source codes: [codesandbox.io/s/withered-water-qf8e8?file=/src/App.js](https://codesandbox.io/s/withered-water-qf8e8?file=/src/App.js)

Okay, thanks! I didn't know the touch and click events were competing like that.

> But our problem was not about event bubbling. I will try to explain more clearly.
> First of all, onClick events are triggered after we release the mouse button or release the touch.
> 
> ```
> - a
>   - b
>     - c
>   - d
> ```
> 
> Think about the case above, when the cursor is on `c` and we touch the thought 'd', context 'b' will be collapsed, and We won't have released the touch yet, the current touch position will be on Content div, and after we release the touch, the onClick event of Content div will be triggered.

Got it, that makes sense now!

2021-05-11 22:52 UTC, onurpolattimur commented
I made an in-depth review. I think the only option is that using the onMouseDown event instead of onClick. I explained the reason why we should not use onClick above. 

But when we use onMouseDown, another issue will occur. Because click/touch operation is not completed yet selection will be on Editable, so it will not pass the condition below.

So I added a guard, to make sure onClick is triggered only if the user starts the action by pressing the Content element.

https://github.com/cybersemics/em/blob/a08761ac79377927e39630451df47644a6104f96/src/components/Content.tsx#L108-L110

2021-05-12 00:30 UTC, merged