#1046 Fade Out Alert
cybersemics/em pull request #1146
Opened 2021-05-14 16:29 UTC by linghong

I didn't find any code has fade time 300 ms, but I noticed that the Alert.tsx had fade out time 200 ms, and disappeared immediately after the timer expired. Actually,  it  turned out the code has no error,  just because the time was too short, the fade out was hardly recognized by human eyes. I thus increased the time to 800 ms.

2021-05-14 20:10 UTC, raineorshine requested changes
Great! That's good that the CSSTransition was already in place. It feels good for the fade-out, but now the fade-in is too long. The fade-in should still be 200ms. You may have to look up how to have separate fade-out and fade-in durations in the `react-transition-group` documentation.

Please revert the formatting changes that were made to `App.css`. This changes the style and lengthens many expressions that would be better in the current more compact format.

2021-05-15 20:43 UTC, linghong commented
Sorry. I didn't notice that the FormateOnSave on my editor was set on true. I have moved the formate back to original.  

I think how it animates is determined by the CSS code, and the JavaScript  code timeout controls the maximum time limit on the animation. Hence, if you want to increase the Alert ease-out  animation time from 800 ms to 2 s, you have to change  the css code fade-enter-active to 2s, and also increase the js code timeout time; while if you want to reduce ease-in animation time, you only need to change the CSS code.

2021-05-15 22:48 UTC, raineorshine commented
> Sorry. I didn't notice that the FormateOnSave on my editor was set on true. I have moved the formate back to original.

Great! The diff is much easier to read too :).

> I think how it animates is determined by the CSS code, and the JavaScript code timeout controls the maximum time limit on the animation. Hence, if you want to increase the Alert ease-out animation time from 800 ms to 2 s, you have to change the css code fade-exit-active to 2s, and also increase the js code timeout time; while if you want to reduce ease-in animation time, you only need to change the CSS fade-enter-active time.

Thanks for the explanation. Looks good to me!

2021-05-15 22:54 UTC, raineorshine approved these changes

2021-05-15 22:55 UTC, merged