Split sentences
cybersemics/em pull request #1168
Opened 2021-05-22 17:22 UTC by linghong

Split sentences when one ore more of symbols  .;!? exist.

It only split sentences when the result will look like real sentences. For example, words like Mr. Jack Smith or $3.2M won't be split. 

An example of sentences that can be split nicely:
call Dr. Smith to schedule an office visit on Sept. 23; remember at least free one full day this week to clean my house!!! call Verizon to ask why it charges me  an extra $35.5 on top of regular bill; buy some fruits tomorrow, e.g. banana, apple, orange; do more exercises (increase to 2 hours per day?)

2021-05-22 17:37 UTC, raineorshine requested changes
Before I do a detailed code review, please make the following changes:

1. Fix failing test
2. Add tests for your new test cases
3. Find a way to implement the desired functionality without mutations. (Mutations are considered a bad practice. The requirement for a more functional programming style is described in the Contributor Guidelines and job posting.)

Thanks and let me know if you have any questions!

2021-05-23 22:36 UTC, linghong commented
I checked your test file. I got really confused. You file is named as splitSentence.ts. But the example thoughts used on your test code is not sentences.  The reason it raises my concern is because in my code if it is Abbrev. word,  such as Dr. or Mr.,  the sentence won't get split. I clarify  an Abbrev. word as the first letter is capital letter, followed by a few small letters and ends with a dot and an empty space.  In your test case the sample sentences is "One. Two. Three.", which match that description.

My question is what is a real use case of your app? Are the thoughts only for listing phrases or words, not for sentences?

2021-05-24 16:48 UTC, raineorshine commented
> I checked your test file. I got really confused. You file is named as splitSentence.ts. But the example thoughts used on your test code is not sentences.

The test cases are short for simplicity but they do demonstrate the expected behavior of `splitSentence`. The length of the sentence should not affect the behavior. For example, the thought "One. Two. Three." should split the same way as "Number One. Number Two. Number Three." or "I have one. I have two. I have three." All of those examples have three sentences ending in periods from the perspective of **em**.

> I clarify an Abbrev. word as the first letter is capital letter, followed by a few small letters and ends with a dot and an empty space.

This is overgeneral and matches many cases that are not abbreviations, as you discovered. We have to whitelist abbreviations, as there is no general way to determine the difference between a sentence ending and an abbreviation without parsing grammar and doing other natural language processing (which **em** does not do).

> My question is what is a real use case of your app? Are the thoughts only for listing phrases or words, not for sentences?

Common use cases of **em** include the user inputting words, phrases, sentences, or paragraphs, either through typing or pasting other sources. `splitSentence` is most useful for pasting a paragraph from a source and then splitting it into sibling thoughts for a more idiomatic structure. 

Entering small words or phrases will be more common than entering abbreviations, so the former should be the base case and the latter should be a special case handled via a whitelist. Let's add a few common abbreviations like "Mr.", "Mrs." and "Dr." and leave it at that for now. We can always add to the list or add more intelligent heuristics later.

2021-05-24 16:53 UTC, linghong commented
Thank you for the detailed explanation. I'll change the abbreviations to a white list.

2021-06-01 03:30 UTC, linghong commented
New modifications:
1.  added test cases;
2. replaced the forEach function with array reduce function to pass through a newly formatted sentence string;
3. added code for dealing with  email and url address;
4. fixed some edge cases.

2021-06-01 12:43 UTC, raineorshine requested changes
Thank you! This turned into a much more complex task than imagined, but you have been extremely thorough! Thanks for writing all the test cases and documenting it so well. It is very clean.

What do you think about ignoring splitter characters that are not followed by whitespace? Sentences are always followed by one or two spaces, so anything that is not followed by whitespace should not be split. I think that may simplify the logic, for example abbreviations, email addresses, etc.

2021-06-01 12:43 UTC, raineorshine commented on src/util/isAbbreviation.ts
> +}
Use a single default export:

```js
export default isAbbrev
```

2021-06-01 12:43 UTC, raineorshine commented on src/util/splitSentence.ts
> +  const seperator = value.indexOf('^^') > 0 ? '^#' : '^^'
This is a good idea, but let's use a dummy value like `__SEP__` instead, which is clearer and even more conflict-proof. Define it as a const at the top of the file, like this:

https://github.com/cybersemics/em/blob/66855eafb13b103520aaee9d0a7a4a60f00346fd/src/util/hashContext.ts#L10

2021-06-01 12:43 UTC, raineorshine commented on src/util/splitSentence.ts
> +    if (i === 0) return newSentence + spliters[0]
There is a typo: `spliters` should be `splitters`. Please do a search and replace to fix all instances of `spliter`.

2021-06-03 02:00 UTC, linghong commented
> What do you think about ignoring splitter characters that are not followed by whitespace? Sentences are always followed by one or two spaces, so anything that is not followed by whitespace should not be split. I think that may simplify the logic, for example abbreviations, email addresses, etc.

I think it is better not split if there is no white space followed by a splitter. By doing that, we still need to have white list for abbreviations, but we can simplify the logic for email and url address.  Or we might do the below way:  we  only split the thought if the first letter followed by the splitter is a Capital letter when there is no empty space immediately after the splitter.  Because, what I am more concern is beside the special cases I have written, I now find other specials ones, such as file names, js library names, IP address. Maybe there are even more we will find later. However, it seems that the complex issue most comes from the "." symbol.  Hence, I think another way we can do is that we make the default condition as below: if the splitter is a dot, we only split the thought when it has empty spaces after the dot, but for other splitters we will still split them.

2021-06-03 17:35 UTC, linghong commented
> Yes, I totally agree!
> 
> Thanks for sticking with it 🙂

I would like to be clear, for the three default rules I mentioned before, which way do you prefer?
1. Do not split the thought if there is no white space followed by a splitter. 
2. Only split the thought if the first letter followed by the splitter is a capital letter when there is no empty space immediately after the splitter.
3. Only split the thought when it has empty spaces after the dot, but for other splitters we will still split them no matter it has white spaces or not.

2021-06-04 09:51 UTC, raineorshine commented
Let's go with #<b/>3!

2021-06-05 11:33 UTC, raineorshine commented on src/util/isAbbreviation.ts
> +}
Oops! I actually got this wrong. You were right the first time :). No problem though.

2021-06-05 11:33 UTC, raineorshine approved these changes
Thank you!!!

2021-06-05 11:34 UTC, merged