Generalize shouldHide in subthoughts
cybersemics/em pull request #1214
Opened 2021-06-03 10:56 UTC by shresthabijay

fixes #1181

2021-06-03 10:56 UTC, shresthabijay commented
@raineorshine I have made the changes. Please review it. Thanks!

2021-06-03 12:10 UTC, raineorshine commented
Confirmed fixed, though there is a regression in the table view. The comment you deleted was a hint.

We currently don't have any test coverage for autofocus, so that would be a useful place to start. We're going to need it if we turn up other bugs, want to refactor anything, or want to add new autofocus functionality (such as customizable expansion depth).

What do you think about RTL tests (e.g. as used in [toggleSort](https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/toggleSort.ts)) with [isElementHIddenByAutoFocus](https://github.com/cybersemics/em/blob/dev/src/util/isElementHiddenByAutoFocus.ts)? Lighter weight than e2e but still provides DOM testing.

Here's the regression:

## Steps to Reproduce

```js
- a
  - =view
    - Table
  - b
    - c
  - d
    - e
```

Set the cursor on `a/b/c`

## Current Behavior

2a0d9ef

`a/b/e` is hidden.

## Expected Behavior

`a/b/e` should be visible.

When the cursor is on a table grandchild leaf (column 2), other grandchildren of the table should be visible.

2021-06-03 12:11 UTC, raineorshine requested changes
Confirmed fixed, though there is a regression in the table view. The comment you deleted was a hint.

We currently don't have any test coverage for autofocus, so that would be a useful place to start. We're going to need it if we turn up other bugs, want to refactor anything, or want to add new autofocus functionality (such as customizable expansion depth).

What do you think about RTL tests (e.g. as used in [toggleSort](https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/toggleSort.ts)) with [isElementHIddenByAutoFocus](https://github.com/cybersemics/em/blob/dev/src/util/isElementHiddenByAutoFocus.ts)? Lighter weight than e2e but still provides DOM testing.

Here's the regression:

## Steps to Reproduce

```js
- a
  - =view
    - Table
  - b
    - c
  - d
    - e
```

Set the cursor on `a/b/c`

## Current Behavior

2a0d9ef

`a/b/e` is hidden.

## Expected Behavior

`a/b/e` should be visible.

When the cursor is on a table grandchild leaf (column 2), other grandchildren of the table should be visible.

2021-06-04 03:22 UTC, shresthabijay commented
> Confirmed fixed, though there is a regression in the table view. The comment you deleted was a hint.
> 
> We currently don't have any test coverage for autofocus, so that would be a useful place to start. We're going to need it if we turn up other bugs, want to refactor anything, or want to add new autofocus functionality (such as customizable expansion depth).
> 
> What do you think about RTL tests (e.g. as used in [toggleSort](https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/toggleSort.ts)) with [isElementHIddenByAutoFocus](https://github.com/cybersemics/em/blob/dev/src/util/isElementHiddenByAutoFocus.ts)? Lighter weight than e2e but still provides DOM testing.
> 
> Here's the regression:
> 
> ## Steps to Reproduce
> ```js
> - a
>   - =view
>     - Table
>   - b
>     - c
>   - d
>     - e
> ```
> 
> Set the cursor on `a/b/c`
> 
> ## Current Behavior
> [2a0d9ef](https://github.com/cybersemics/em/commit/2a0d9efcfc9c09bfffe0a29da9c1a382d6c13c5b)
> 
> `a/b/e` is hidden.
> 
> ## Expected Behavior
> `a/b/e` should be visible.
> 
> When the cursor is on a table grandchild leaf (column 2), other grandchildren of the table should be visible.

I thought I tested this case but it turns out I tested with second columns having children.

2021-06-04 03:25 UTC, shresthabijay commented
> What do you think about RTL tests (e.g. as used in [toggleSort](https://github.com/cybersemics/em/blob/dev/src/shortcuts/__tests__/toggleSort.ts)) with [isElementHIddenByAutoFocus](https://github.com/cybersemics/em/blob/dev/src/util/isElementHiddenByAutoFocus.ts)? Lighter weight than e2e but still provides DOM testing.

Turns out JSDOM doesn't load any stylesheets and also does not changes styles on class toggles. So it may not be easy to get style properties using `getComputedStyle`. I tried it and it doesn't have any necessary styles like opacity and color. I think we should use e2e test for this.

2021-06-04 03:26 UTC, shresthabijay commented
@raineorshine I have made the changes. Both the cases are working properly now. We should add tests for the visibility of thoughts as a separate issues.

2021-06-04 11:29 UTC, raineorshine requested changes
`a/b/c` should be visible and dimmed.

![image](https://user-images.githubusercontent.com/750276/120794657-bead6b80-c4f5-11eb-83f6-2755f350f600.png)

2021-06-04 11:29 UTC, raineorshine commented on src/components/Subthoughts.tsx
> +  .some((child: Child) => !isFunction(child.value))
I'm not sure how this logic was working before, but it doesn't take into account `showHiddenThoughts`. You can use the `hasChildren` predicate selector instead:

https://github.com/cybersemics/em/blob/5101be65c855fe7e1a18adeb4efd62183d12c6c5/src/selectors/getChildren.ts#L46-L52

2021-06-04 11:31 UTC, raineorshine commented
> Turns out JSDOM doesn't load any stylesheets and also does not changes styles on class toggles. So it may not be easy to get style properties using `getComputedStyle`. I tried it and it doesn't have any necessary styles like opacity and color. I think we should use e2e test for this.

Ah, that's good to know. We could test against `distance-from-cursor-x` with JSDOM though. Not sure if that's ideal given that `distance-from-cursor` itself is the wrong semantics and needs to be refactored according to a more unified set of autofocus rules.

2021-06-08 16:34 UTC, shresthabijay commented
> We could test against `distance-from-cursor-x` with JSDOM though. Not sure if that's ideal given that `distance-from-cursor` itself is the wrong semantics and needs to be refactored according to a more unified set of autofocus rules.

Totally agreed. It takes a while to understand how the autofocus affects the visibility and position of the thoughts. The main problem is that the `distance-from-cursor-x` approach only takes depth into account. But some thoughts needs to hidden or dimmed because of their relative position to the cursor and also may due to meta attributes. We need to do calculations to find the edge cases and fix them anyways. We can write a selector that determines the visibility and position of the thought given the current state and its path. It will be easier to test too.

2021-06-08 21:39 UTC, raineorshine approved these changes
Thank you, this works great, and the tests are a good short term solution until we have better visibility logic and detection!

2021-06-08 21:39 UTC, merged

2021-06-09 03:26 UTC, shresthabijay commented on src/components/__tests__/Visibility.ts
> +import { ReactWrapper } from 'enzyme'
Sure. I will keep that in mind. Thanks!