Fix expandThoughts regression
cybersemics/em pull request #1241
Opened 2021-06-10 08:00 UTC by shresthabijay

fixes #1238

2021-06-10 08:00 UTC, shresthabijay commented
@raineorshine Please review the change. Thank you!

2021-06-10 15:05 UTC, raineorshine requested changes
Looks good! Can you add a unit test at your convenience?

2021-06-11 04:38 UTC, shresthabijay commented
@raineorshine  I have added the test.

2021-06-11 21:53 UTC, raineorshine approved these changes

2021-06-11 21:53 UTC, merged