Dismiss gesture hint when gesture is abandoned on scroll
cybersemics/em pull request #1292
Opened 2021-06-19 07:34 UTC by onurpolattimur

fixes: #1242

2021-06-19 21:29 UTC, raineorshine requested changes
Thanks! It is an improvement, though it still happens sometimes unfortunately. It's even harder to reproduce now. I can reproduce it most consistently when the scrollbar is completely still at the start, and the final down swipe is just a few pixels long. If you are unable to reproduce then I will have to get remote debugging working and try to track the touchmove events.

Architecturally, we need to take a slightly different approach. The `MultiGesture` component should not know about the global store or gesture hints. I suggest adding a new event handler `onCancel` that allows the upstream component to add the appropriate logic.

2021-06-20 17:13 UTC, onurpolattimur commented
I could reproduce only once but I made some changes. Can you check it again, please?

2021-06-28 13:48 UTC, raineorshine reviewed
It still occurs consistently for me unfortunately. Would you like to keep working on it or shall I give it a try?

2021-06-28 13:48 UTC, raineorshine commented on src/components/MultiGesture.tsx
> +          }
You can also use the fancy new [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) operator: `this.props.onCancel?.()`

2021-06-28 18:10 UTC, onurpolattimur commented
> It still occurs consistently for me unfortunately. Would you like to keep working on it or shall I give it a try?

I can't re-produce still after 8384ab9. So you can give it a try if you want.

2021-07-01 22:29 UTC, raineorshine commented
@onurpolattimur The main issue was the scrolling was causing the `MultiGesture` to terminate without `onPanResponderRelease` (and thus `onEnd`) being called.

In order to make the gesture system more forgiving, we currently allow a tiny bit of scroll without abandoning the gesture. Unfortunately, in the case of this issue, `onPanResponderRelease` is not called, even after `touchend`. Neither is `onPanResponderReject` or `onPanResponderEnd`.

`onPanResponderTerminate` is called consistently, but it is also called for any scroll event. I am not aware of a way to differentiate when `onPanResponderTerminate` is called from a scroll event vs a final termination where release it never called.

So instead of eliminating the scroll lenience, we can handle `touchend` manually and ensure `onEnd` is called if there is a valid sequence.

```ts
    document.body.addEventListener('touchend', e => {
      if (this.sequence) {
        setTimeout(() => {
          if (!this.abandon && this.sequence) {
            this.props.onEnd?.(this.sequence, e as unknown as GestureResponderEvent)
            this.reset()
          }
        })
      }
    })
```

I also cleaned up some state access that was happening outside of a thunk, which could lead to timing issues, but I don't think that was causing the problem.

2021-07-01 22:30 UTC, raineorshine commented
Apparently I can't request a review from you since you created the PR, but feel free to take a look.

2021-07-02 15:22 UTC, onurpolattimur commented
Hi @raineorshine. Glad you found it.
I reviewed and it looks good to me.

2021-07-03 00:43 UTC, raineorshine approved these changes

2021-07-03 00:44 UTC, merged