Empty thought with formatting tags breaks caret
cybersemics/em pull request #1515
Opened 2022-02-13 13:46 UTC by karunkop

Fixes #1502 #1503 #1504 

## Problem

- Caret use to disappear when pasting/writing empty formatting tags i.e `<b></b>` and then hitting enter and backspace
- A subscript as `2` used to appear after hitting enter when pasting/writing empty formatting tags.

## Solution

- Strip all empty formatting tags if there are any
-  In `ThoughtAnnotation.tsx` check the value after stripping empty tags. If not this will result in `2` to appear as subscript under empty thought.
- Set selection cursor offset to 0 if there is an empty thought ultimately resolving the disappearing of caret issue.

2022-02-14 15:48 UTC, raineorshine requested changes
After a thorough review, I think it would be better if we removed empty formatting tags completely during editing, just like we do on paste. The resulting code is more consolidated, avoids adding complexity to `setSelectionToCursorOffset`, preserves the universality of the `value` variable, and indirectly handles other issues not handled by this solution (e.g. `deleteEmptyThought` should delete `<b></b>`).

Try stripping the empty tags [when `newValue` is set](https://github.com/cybersemics/em/blob/11d25eb2cf982fc76330ce6c01af3b0e8f0ed4df/src/components/Editable.tsx#L454). Let me know if you run into any issues with this approach, or if I am missing something!

2022-02-15 14:29 UTC, karunkop commented on src/util/normalizeThought.ts
> +}
Sure

2022-02-15 15:30 UTC, raineorshine approved these changes
Looks good, thanks!

2022-02-15 15:30 UTC, raineorshine commented on src/components/Editable.tsx
> +      : stripEmptyFormattingTags(oldValue)
`stripEmptyFormattingTags` does not need to be called on `oldValue`, since `oldValue` merely contains the last `newValue` and is already stripped.

2022-02-15 15:31 UTC, merged