Update cursor after thought deletion
cybersemics/em pull request #1517
Opened 2022-02-14 08:25 UTC by shresthabijay

fixes #1455 

## Cause of the issue

After thought deletion the cursor was not updated causing `expandThoughts` function to panic.

## Solution

Update the cursor after thought deletion.

2022-02-14 15:58 UTC, raineorshine requested changes
Thanks! Can you add a unit test?

2022-03-10 14:05 UTC, shresthabijay commented on src/selectors/expandThoughts.ts
>    }
This is not expected under normal conditions. This indicated we are calling this function with the wrong path or path that is not available in the tree. So I think we must fail hard.

2022-03-20 10:42 UTC, shresthabijay commented
@raineorshine I added hard failure if the given path is incorrect in `expandThoughts`. I added proper tests for updating the cursor after thought deletion.

Also, there was this issue with undo-redo after I added hard failure. Turns out it was due to a stale cursor. I have fixed it and  added a comment describing why it is needed. 

https://github.com/cybersemics/em/blob/55d1b817781da3f402baf8a2dad01f5c580b3b33/src/redux-enhancers/undoRedoReducerEnhancer.ts#L37-L47.

I believe this should work now.

2022-03-20 18:16 UTC, raineorshine approved these changes

2022-03-20 18:18 UTC, merged