Bold Text disappears
cybersemics/em pull request #1544
Opened 2022-03-31 14:35 UTC by karunkop

Fixes #1540 

## Problem

- The regex expression used for stripping empty formatting tags in `stripEmptyFormattingTags.ts` was considering `b` and `r` also as a valid expression for this case due to which they were being stripped off.

## Solution

- Modified regex expression to avoid above mentioned problem

2022-03-31 14:38 UTC, raineorshine commented
Thanks! Please add a unit test.

2022-03-31 17:02 UTC, raineorshine commented
I was thinking an integration-level test, i.e. emulating user behavior. `stripEmptyFormattingTags` is pretty fairly self-explanatory from the regexp. 

I would suggest writing a test that either dispatches an `editThought` action or an RTL test that emulates editing the thought component. There are examples of both in some of the `__test__` folders.

2022-03-31 17:03 UTC, raineorshine requested changes
I was thinking an integration-level test, i.e. emulating user behavior. `stripEmptyFormattingTags` is pretty fairly self-explanatory from the regexp itself. 

I would suggest writing a test that either dispatches an `editThought` action or an RTL test that emulates editing the thought component. This will provide better coverage of the full stack. There are examples of both in some of the `__tests__` folders.

2022-04-01 02:38 UTC, karunkop commented
> I was thinking an integration-level test, i.e. emulating user behavior. `stripEmptyFormattingTags` is pretty fairly self-explanatory from the regexp itself.
> 
> I would suggest writing a test that either dispatches an `editThought` action or an RTL test that emulates editing the thought component. This will provide better coverage of the full stack. There are examples of both in some of the `__tests__` folders.

Sorry i completely missed this comment yesterday. Will do that today. Thanks!

2022-04-01 13:23 UTC, raineorshine requested changes
This test is the right idea, although you're going to have to implement it as an integration test (with a functioning DOM) instead of a pure reducer test, because the bug doesn't actually occur in the reducers. Take a look at the tests in `shortcuts` or `components`.

If you try the test on `dev`, you'll notice that it actually passes (without your fix), which tells us that it doesn't test what you think it tests. I recommend always making sure your test fails without the fix. That is just as important as making the test pass with the fix.

2022-04-01 13:46 UTC, karunkop commented
> This test is the right idea, although you're going to have to implement it as an integration test (with a functioning DOM) instead of a pure reducer test, because the bug doesn't actually occur in the reducers. Take a look at the tests in `shortcuts` or `components`.
> 
> If you try the test on `dev`, you'll notice that it actually passes (without your fix), which tells us that it doesn't test what you think it tests. When writing tests, I recommend first making sure your test fails without the fix. That is just as important as making the test pass with the fix.

Thanks for the advice, I will right this test with a functioning DOM shortly now

2022-04-01 16:38 UTC, raineorshine approved these changes
Works perfectly! Thanks!

2022-04-01 16:38 UTC, raineorshine commented on src/components/__tests__/Thought.ts
> +  windowEvent('keydown', { key: 'Backspace' })
The Backspace is actually unnecessary.

2022-04-01 16:45 UTC, merged