Adding individual drag hover and drag target test and updated snapshots
cybersemics/em pull request #2074
Opened 2024-06-25 13:55 UTC by Zubair286

#1902

2024-06-25 20:05 UTC, raineorshine requested changes

2024-06-25 20:05 UTC, raineorshine commented on src/e2e/puppeteer/__tests__/snapshot.ts
> +  it('Check drop target tests, covering DropUncle', async () => {
Please follow the instructions that were given for this test. The cursor needs to be on `c` for the `DropUncle` component to be rendered. Please review the [wiki](https://github.com/cybersemics/em/wiki/Docs#7-drag-and-drop) and check out the [DropUncle component](https://github.com/cybersemics/em/blob/472472069b4637a88c9bbb14f2ce6918ad742b1e/src/components/DropUncle.tsx#L17) if you are unclear about how `DropUncle` is rendered.

> 3\. A test that covers `DropUncle` (with the cursor on `c`)

2024-06-26 11:11 UTC, Zubair286 commented on src/e2e/puppeteer/__tests__/snapshot.ts
> +  it('Check drop target tests, covering DropEnd', async () => {
Just one thing, the drag is initiated here but you mentioned `dragAndDrop` is not needed, can you explain this a little?

2024-07-01 22:20 UTC, raineorshine approved these changes
Looks great! Thank you.

I had to add a small delay after the first click in the uncle tests. Otherwise on my machine the thought didn't expand in time for the second click.

I generated the macos snapshots.

2024-07-01 22:44 UTC, merged