fixed drop-hover position on first column last thought in table view
cybersemics/em pull request #2125
Opened 2024-07-09 07:31 UTC by Zubair286

2024-07-09 14:22 UTC, raineorshine requested changes
For #1887, the drop hover needs to be positioned with its left edge flush with the left edge of col1, regardless of the length of thoughts in col1. In this example with longer thoughts in col1, the drop hover is too far to the right:

```
- a
  - =view
    - Table
  - =pin
    - true
  - Boston
    - c
  - Denver
    - e
- x
```

![Preview 2024-07-09 10 08 19](https://github.com/cybersemics/em/assets/750276/fb91ac07-5732-43dc-91a1-0c50cac69e83)

Please add a snapshot test for each issue as well. Thanks!

2024-07-09 19:10 UTC, Zubair286 commented
I think I should make a separate PR for #1886 if the solution is good for that.

2024-07-09 19:48 UTC, raineorshine commented
Yes, a separate PR for each issue is preferred. 

Please make sure to describe the cause of the problem as well once you identify. That will help determine the appropriateness of the solution.

2024-07-10 10:33 UTC, Zubair286 commented
One thing I want to ask is that in the table view initially the columns are too far to the left until x is dragged after d, then the columns shifts to right, my guess is that the drop-hover is rendering to the right before the drag, shouldn't the columns already be in the position move to after drag?

2024-07-10 11:59 UTC, raineorshine commented
Hmmm good point. That’s a bug in the table view. We may want to wait until that’s fixed to confirm if this is still an issue.

2024-09-18 05:56 UTC, trevinhofmann commented
@Zubair286, it appears that this issue has been resolved (by #2175?):

https://github.com/user-attachments/assets/736f52da-01e6-4c7c-8bbe-81aeaf4aaadf

Can this pull request be closed, or does more need to be done?

2024-09-19 15:08 UTC, Zubair286 commented
Yes, this pull request can be closed.

2024-09-21 09:19 UTC, closed without merging