#2084 fix: assign single line height on truncated url line
cybersemics/em pull request #2131
Opened 2024-07-10 06:07 UTC by baproactive

2024-07-10 12:19 UTC, raineorshine requested changes
First, start with describing the cause of the bug. *Why* is the height incorrect? It is hard for me to evaluate if the solution is appropriate without knowing the cause of the bug. 

I am guessing that `useMultiline` is returning true for the multiline url, and stays that way even when the url is ellipsized. If so, wouldn't we want to correct the problem there? Hard coding the height would seem to only mask the problem.

2024-07-10 15:24 UTC, baproactive commented
> First, start with describing the cause of the bug. _Why_ is the height incorrect? It is hard for me to evaluate if the solution is appropriate without knowing the cause of the bug.
> 
> I am guessing that `useMultiline` is returning true for the multiline url, and stays that way even when the url is ellipsized. If so, wouldn't we want to correct the problem there? Hard coding the height would seem to only mask the problem.

It's not affected by multiline flag, it's affected because of the display:inline-block applied to .single-line .thought-annotation .editable-annotation-text
browser calculates the height differently between display:inline-block and display: inline. 

For those annotation boxes under .single-line class name, they have display:inline-block to apply the css text sllipsis style.

2024-07-10 18:00 UTC, raineorshine requested changes
Got it, thanks. Let's add an inline comment explaining that. 

Where is the other `1.9em` defined? It might be a good idea to define that in one place if they are tightly coupled. Otherwise that relationship is not explicit and it's more likely that one might be changed accidentally.

2024-07-12 16:00 UTC, raineorshine approved these changes

2024-07-12 16:00 UTC, raineorshine commented on src/App.css
> +    .singl-line element has display: inline-block property, it affects the height calculation of the .thougt div so we need to set the height manually.
Good comment, thanks.

2024-07-12 16:00 UTC, raineorshine commented on src/App.css
> +    This height 1.9em is the same value as the min-height above: line: 630
We should avoid specifying exact line numbers in comments, as they are quickly invalidated if any code is added or removed above.

2024-07-12 16:00 UTC, raineorshine commented on src/App.css
> +  height: 1.9em;
We can leverage CSS variables for a more explicit enforcement of using the same value across multiple properties.

2024-07-12 16:00 UTC, merged