PandaCSS - shortcuts table + add conditions
cybersemics/em pull request #2373
Opened 2024-09-06 21:27 UTC by yangchristina

2024-09-06 22:06 UTC, raineorshine requested changes
Thank you! Here are the issues I'm seeing.

# 1. Command Palette

## Steps to Reproduce

Activate the Command Palette (⌘+P).

## Current Behavior

7cbffa6dd5

<img width="753" alt="Brave Browser 2024-09-06 17 36 53" src="https://github.com/user-attachments/assets/82264103-f774-4187-a039-60a3be6f03eb">

## Expected Behavior

`main`

<img width="753" alt="Brave Browser 2024-09-06 17 36 38" src="https://github.com/user-attachments/assets/2c4ce46f-8908-420a-a357-ac9a9c98f2fc">

# 2. Help Screen

## Steps to Reproduce

Click the (?) icon in the footer to open the Help screen.

## Current Behavior

`main` (1821f84951)

<img width="754" alt="Brave Browser 2024-09-06 17 39 10" src="https://github.com/user-attachments/assets/968788e1-ad4f-4905-bcf1-4af8f6ad0261">

## Expected Behavior

1821f84951 (or any commit before 1821f84951)

<img width="753" alt="Brave Browser 2024-09-06 17 39 34" src="https://github.com/user-attachments/assets/57e254eb-0fd2-4160-980b-fd13332193a8">

# 3. Gesture Library

## Steps to Reproduce

Help → Gesture Library

## Current Behavior

Margins have changed.

<img width="753" alt="Brave Browser 2024-09-06 17 47 56" src="https://github.com/user-attachments/assets/ba1911ac-1bf8-4153-bdd7-181eb47b6f3d">

## Expected Behavior

Layout should be unchanged.

<img width="753" alt="Brave Browser 2024-09-06 17 48 51" src="https://github.com/user-attachments/assets/8c72cdf6-b0f8-41b7-9877-3165d749a1f0">

2024-09-06 22:06 UTC, raineorshine commented on src/components/ShortcutRow.tsx
> +        <td className={css({ minWidth: { base: '10rem', _mobile: 'auto' }, textAlign: { _mobile: 'center' } })}>
Looks good 👍

2024-09-07 00:21 UTC, yangchristina commented
@raineorshine I'm not sure if I have the same as you, but I don't have that showing:
<img width="1721" alt="Screenshot 2024-09-06 at 5 20 36 PM" src="https://github.com/user-attachments/assets/ceb2b9da-47bc-4b3d-9995-ca5e4f9cdfb3">

2024-09-07 00:46 UTC, yangchristina commented
I added a fix for the modal z-indices. I don't think I was the one to introduce this bug, since I'm pretty sure all modals before where using the `popover` class, and therefore the `popover` z-index, but it also could have been me.

2024-09-07 13:41 UTC, raineorshine requested changes
> @raineorshine I cannot reproduce the issues

Thanks for confirming! There must be some vite caching that I'm not used to yet.

> I added a fix for the modal z-indices. I don't think I was the one to introduce this bug, since I'm pretty sure all modals before were using the popover class, and therefore the popover z-index, but it also could have been me. Either way it's not one that really causes problems.

Great, thanks! Could you actually add a z-index in between modal and pop-up for the command palette? It is possible (though uncommon) for all three to be open at once. I didn't anticipate this when I originally gave it the modal class.

2024-09-07 19:11 UTC, yangchristina commented
@raineorshine yes there actually is a --z-index-command-palette between the two, it's just not being used (currently command palette uses popup z-index)

2024-09-07 19:14 UTC, raineorshine commented
Great. Please go head and change the command palette to use it. I'm not sure what happened there.

2024-09-07 19:30 UTC, raineorshine approved these changes
I forgot that the CommandPalette was actually rendered as a `<Popup>`. This should work though!

2024-09-07 19:35 UTC, raineorshine approved these changes

2024-09-07 19:46 UTC, merged