Pandacss anchor buttons
cybersemics/em pull request #2407
Opened 2024-09-21 22:47 UTC by yangchristina

This is the last of the element selectors in App.css

2024-09-22 21:34 UTC, yangchristina commented
I failed a puppeteer test earlier: https://github.com/cybersemics/em/actions/runs/10983149534/job/30492188860?pr=2407

I make some small changes that wouldn't make any difference really, and the tests are passing now. I also couldn't find any connection between the failing snapshot and the code in my last commit, which seems odd.

2024-09-24 11:30 UTC, trevinhofmann requested changes
Aside from the one suggestion about `.context-chain` cleanup, this pull request looks good to me. Thanks, @yangchristina!

2024-09-24 11:30 UTC, trevinhofmann commented on src/components/AppComponent.tsx
> -      <GlobalStyles styles={globalStyles} />
Awesome! 🎉

2024-09-24 11:30 UTC, trevinhofmann commented on src/App.css
> -}
While we're removing the unused `.context-chain`, now would be a good time to clean up the other references to it by removing these comments? https://github.com/cybersemics/em/blob/25cbb95a8ac01a42540d93a459eaef5e9d4f1498/src/App.css#L685-L713

2024-09-24 17:18 UTC, trevinhofmann approved these changes

2024-09-24 18:33 UTC, raineorshine approved these changes

2024-09-24 18:34 UTC, merged