Add puppeteer video recorder helper
cybersemics/em pull request #2463
Opened 2024-10-19 04:43 UTC by mstrofbass

Proposal to add a Puppeteer video recording helper to make it easier to debug puppeteer tests.

I'm going to be using this regardless of whether it's merged or not; I just figured I'd offer it up since it may prove to be useful for others.

2024-10-19 04:45 UTC, mstrofbass commented
This has puppeteer-screen-recorder pinned to version 3.0.3 because 3.05 seems to have a bug with the build/packaging that breaks importing. It should be unpinned once that is resolved in the dependency.

2024-10-19 06:35 UTC, raineorshine requested changes
Sure! This looks useful.

2024-10-19 06:35 UTC, raineorshine commented on src/e2e/puppeteer/helpers/recordVideo.ts
> +async function init() {
`init` should not be async

2024-10-19 07:38 UTC, mstrofbass commented on src/e2e/puppeteer/helpers/recordVideo.ts
> +async function init() {
Good catch!

2024-10-19 07:40 UTC, mstrofbass commented
When I start using it a little more I'll look into configuring a directory and then adding that directory to the .gitignore. We could probably just add `*.mp4` to the .gitignore file for now as well, but I should have a more robust solution soon enough.

2024-10-19 07:40 UTC, merged

2024-11-24 09:12 UTC, raineorshine commented
FYI I decided to remove puppeteer-screen-recorder because the ffmpeg dependency was a bit heavy and it's not being actively used by the team.