fix : gap between thoughts
cybersemics/em pull request #2609
Opened 2024-11-22 16:46 UTC by RED-ROSE515

Issue : Gap between thoughts #2510

Currently there is unexpected gaps between thoughts.
And it's because of clipPath in editable recipe.
So, I removed clipPath.

2024-11-22 17:05 UTC, raineorshine requested changes
`clipPath` is there for a reason, which is documented in the inline comment. You will need to investigate what functionality it is providing, what is lost by its removal, and what an adequate replacement could be.

If it is no longer needed, you will need to provide a convincing argument as to why this has changed.

2024-11-22 17:16 UTC, RED-ROSE515 commented
Yeah, currently, the clipPath is used to prevent incorrect selection behavior when clicking on the edges of an editable element.

2024-11-22 17:45 UTC, RED-ROSE515 commented
@raineorshine , What do you think about adding margin top and bottom, instead of removing clipPath?

2024-11-22 17:47 UTC, raineorshine commented
I'm not sure. You will have test it and see if the desired selection behavior is preserved across platforms and font sizes.

2024-11-22 18:58 UTC, RED-ROSE515 commented
@raineorshine , Could you tell me what is the original one, and what is new generated one?
![drag-drop-hover-after-first-thought-of-column-one-1-diff](https://github.com/user-attachments/assets/8a0f587f-aa7c-48a2-a8a2-1ebf7bc7cb58)

2024-11-23 08:13 UTC, raineorshine commented
If margin doesn't work, another idea is to shift the `y` positioning up since thoughts are absolutely positioned.

2024-11-23 18:42 UTC, RED-ROSE515 commented
I think margin is good right now.

2025-01-06 16:44 UTC, closed without merging

2025-01-06 16:44 UTC, raineorshine commented
Closing in favor of #2656.