Fix failing note cursor
cybersemics/em pull request #2735
Opened 2024-12-25 23:19 UTC by snqb

it was `onFocus` of a newly created not that triggered

```
const simplePath = simplifyPath(state, path) || path
.
.
.
setCursor({
  path: simplePath,
  .
  .
}
```

the problem was: `simplifyPath` would return an empty array at times like this.
The and we'd get `simplifyPath(state, path) || path) = `[] || path` = `[]` , so the fallback never really worked 😄 

After putting a more elaborate condition, and using `path` as a fallback, we get broken editor behavior: the part of the tree collapses(we go to a wrong `path`)

In the end, when I just did not allow `[]` paths, it fixed the thing. And the app, from my manual tests, works just fine. The cursor is there, everything is smooth.
`setDescendant` action puts the appropriate state, from what I observed.

and on the reasons why we even get to the case of `simplifyPath` returning `[]` here, I'm not really sure, and feels like, we should dig there, if we want more than just a ad-hoc bug fix.

2024-12-26 22:00 UTC, raineorshine requested changes
Hi, thanks for your submission and for identifying that `simplifyPath` returns `[]`.

As you know we maintain high code quality standards on this project, so I'm not able to accept an ad-hoc fix. For all bugs, we expect to identify the root cause which will inform an appropriate solution. In rare cases we may determine that the effort to create a proper solution is not justified, but that is not the case here. I would encourage you to trace `simplifyPath` to determine what is causing it to return `[]`. 

`[]` is not a valid Path, but it's not covered by the type system so we have to manually trace where it's coming from.

2025-01-14 06:49 UTC, trevinhofmann commented
Hi, @snqb. Thank you very much for the initial pull request. Please let me know if you need any further guidance to proceed.

2025-01-17 14:09 UTC, snqb commented
yeah, the first submission was just seeing the thing, then I got distracted with other tasks
sorry for having this open for a while, I guess it's not a good practice to keep things open for so long

The more I looked at the issue, the more it seeems to me that doing a `setCursor` is wrong, simplifying the path was wrong too
and I don't quite get why we want to clear the cursor history while focusing on a note.

so the end solution revolves just around manually dispatching `editing + setNoteFocus`
the cursor is already handled anyways
```tsx
/** Sets the cursor on the note's thought as it is being edited. */
  const onFocus = () => store.dispatch([editing({ value: true }), setNoteFocus({ value: true })])
```
and it kinda rhymes with 

```tsx

  /** Set editing to false onBlur, if keyboard is closed. */
  const onBlur = () => {
    if (isTouch && !selection.isActive()) {
      setTimeout(() => dispatch(editing({ value: false })))
    }
  }
```


but since also, the `noteFocus` action does change the `editing`
```tsx
...
  noteFocus: value,
  // always enter edit mode when there is note focus
  // it will be set in the Note's onFocus anyway, but set it here so that we are not as dependent on what happens there
  ...(value ? { editing: true } : null),
```

the end function could be just
`const onFocus = () => store.dispatch(setNoteFocus({ value: true }))`

From the preliminary clicking around: it works just fine, and also solves the original issue.
Also, tests seem to pass fine too. Let me know if I missed something, but the solution sounds logical to me.

2025-01-17 14:11 UTC, snqb commented on src/components/Note.tsx
> +  const onFocus = () => store.dispatch(setNoteFocus({ value: true }))
diff from the original fn:

setCursor({
      ~path: simplePath~, // does not simplify a path, we don't need it
      ~cursorHistoryClear: true~, // why do we need it?
      editing: true, // does it inside `setNoteFocus`
      noteFocus: true, // does it via `setNoteFocus`
    })

2025-01-18 10:46 UTC, raineorshine reviewed
Thanks for your submission. We need the `setCursor` actually. If the user clicks on the note of a non-cursor thought, the cursor needs to move to that thought.

2025-01-18 10:48 UTC, raineorshine commented
As I was investigating the code to form a proper reply, it became clear that the use of `simplePath` was incorrect and the Note just needed to use `path` instead. I made the fix in e8dbc42b9e.

The case could still use an RTL test. Is this something you could do?

2025-01-18 10:48 UTC, closed without merging