Third bunch of possible undefined thoughts
cybersemics/em pull request #2744
Opened 2024-12-28 23:47 UTC by snqb

fixes #2711

2024-12-28 23:55 UTC, snqb commented
a couple test cases failing, will fix later

2024-12-28 23:56 UTC, snqb commented on src/selectors/parentOfThought.ts
> +  return parentThought ?? null
preserve fn signature

2024-12-29 00:01 UTC, snqb commented on src/stores/commandStateStore.ts
> +      : getCommandState(pathToThought(state, state.cursor)?.value ?? '')
on that end we have a `path.length === 0` default case, so fallback is fine here

2024-12-29 00:05 UTC, snqb commented on src/util/importJSON.ts
> +  const rankIncrement = destEmpty ? getRankIncrement(state, blocks, destThought, rankStart) : 1
1 is a fallback in getRankIncrement too, so that's my judgment

2024-12-29 00:07 UTC, snqb commented on src/test-helpers/deleteThoughtAtFirstMatch.ts
> +  if (!thought) throw new Error(`Thought not found for path: ${path}`)
it's a test file, and we throw an error for empty path above, so thought why not

2024-12-29 00:08 UTC, snqb commented on src/test-helpers/contextToThought.ts
> +  return id ? (getThoughtById(state, id) ?? null) : null
to preserve type for now

but there's an itch to make it `Thought | null | undefined`
wdyt?

2024-12-29 18:03 UTC, raineorshine requested changes
Thanks!

2024-12-29 18:03 UTC, raineorshine commented on src/util/importJSON.ts
> +  if (!thoughtOld) return
Let's return `null` here since `insertUpdates` is nullable below.

2025-01-03 11:39 UTC, snqb commented on src/actions/formatLetterCase.ts
> +    if (originalThoughtValue === undefined) return
I'm not sure if I got you right, but here's what I've ended up with

```typescript
const cursor = state.cursor
if (!cursor) return

const originalThoughtValue = pathToThought(state, cursor)?.value
if (originalThoughtValue === undefined) return
```

2025-01-03 11:42 UTC, snqb commented on src/test-helpers/contextToThought.ts
> +  return id ? (getThoughtById(state, id) ?? null) : null
ok, I made it `Thought | undefined`, and it broke nothing

2025-01-03 20:52 UTC, raineorshine commented on src/actions/formatLetterCase.ts
> +    if (originalThoughtValue === undefined) return
`originalThoughtValue` can only be undefined due to the optional chaining operator. It doesn't really make sense to use it here in order to check for undefined, when what you really want to check is if the thought is undefined. `thought.value` is always a string. There's no reason to get it mixed up with the undefined thought check.

```
const thought = pathToThought(state, cursor)
if (!thought) return
```

2025-01-03 21:04 UTC, raineorshine requested changes

2025-01-03 21:04 UTC, raineorshine commented on src/hooks/useDragAndDropSubThought.ts
> +  }
This `console.warn` is not accurate, as dropping a thought on itself is already detected and short circuited using the `equalPath` check above. Please update the message or remove the `console.warn` completely, combining it with the first return statement.

2025-01-03 21:04 UTC, raineorshine commented on src/hooks/useDragAndDropSubThought.ts
> +  if (!sameContext && thoughtTo && thoughtFrom) {
This isn't necessary due to the short circuit above.

2025-01-03 21:11 UTC, merged