Get simplified context for attribute check in toggle sort
cybersemics/em pull request #998
Opened 2021-01-12 11:11 UTC by shresthabijay

fixes #977 

# Changes
- Use `simplifyPath` to get simplified context for attribute check in `toggleSort`.

2021-01-12 11:13 UTC, shresthabijay commented
@raineorshine I think we should make this changes to other shortcuts too.

2021-01-12 22:23 UTC, raineorshine commented
> @raineorshine I think we should make this change to other shortcuts too.

Yes! Could you do that in this PR for all other shortcuts with `isActive` defined?

2021-01-12 22:24 UTC, raineorshine requested changes
> @raineorshine I think we should make this change to other shortcuts too.

Yes! Could you do that in this PR for all other shortcuts with `isActive` defined?

2021-01-13 17:59 UTC, raineorshine approved these changes

2021-01-13 17:59 UTC, merged